services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  backend:
    image: areda007/clv-task
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"